---
- name: Ensure php apt repo is present.
  apt_repository:
    repo: ppa:ondrej/php
    # filename: php
    update_cache: yes

- name: Ensure apache and php are present.
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - apache2
    - php7.2
    - php7.2-cli
    - php7.2-curl
    - php7.2-json
    - php7.2-ldap
    - php7.2-mbstring
    - php7.2-mysql
    - php7.2-opcache
    - php7.2-phpdbg
    - php7.2-readline
    - php7.2-sqlite3
    - php7.2-xml
    - php7.2-zip
  tags:
    - install

- name: Ensure apache is listening on port 8080.
  lineinfile:
    path: /etc/apache2/ports.conf
    regexp: '^Listen '
    line: 'Listen 8080'
  notify:
    - restart apache

- name: Set default vhost to listen on 8080.
  lineinfile:
    path: /etc/apache2/sites-enabled/000-default.conf
    regexp: '^<VirtualHost \*:80>'
    line: '<VirtualHost *:8080>'
  notify:
    - restart apache
