---
- name: Ensure socket sounds server container is present.
  docker_container:
    name: sounds-server
    image: socketsounds/server
    pull: true
    state: started
    restart_policy: always
    ports:
      - "5000:5000"

- name: Ensure socket sounds client container is present.
  docker_container:
    name: sounds-client
    image: socketsounds/client
    pull: true
    state: started
    restart_policy: always
    ports:
      - "9001:80"
    env:
      SERVER_URL: ws://sounds.caseyfulton.com/
      SOUNDS_URL: http://sounds.caseyfulton.com/sounds/
      
